import { log } from "node:console";

export default async function sendWebhook(BC_WEBHOOK_URL: string, payload: any, signature: string) {
    try {
        log("Sending webhook to:", BC_WEBHOOK_URL);
        const response = await fetch(BC_WEBHOOK_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlBjWDk4R1g0MjBUMVg2c0JEa3poUW1xZ3dNVSIsImtpZCI6IlBjWDk4R1g0MjBUMVg2c0JEa3poUW1xZ3dNVSJ9.eyJhdWQiOiJodHRwczovL2FwaS5idXNpbmVzc2NlbnRyYWwuZHluYW1pY3MuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZWY1NmJiM2MtOTkxNS00YzJhLWIyMGItNzA1MzIxMWU4MWZmLyIsImlhdCI6MTc2OTQxNjQ4NSwibmJmIjoxNzY5NDE2NDg1LCJleHAiOjE3Njk0MjA4OTQsImFjciI6IjEiLCJhaW8iOiJBUVFCKy80YkFBQUF4dStCQ2FxV0RicGwyMU8vN2I2UC9NMnpRVEFVQnd4Wi84MHpNTHZOeHdtczhhakYweUhlSDBqd3JWeVl0SFZ5dzg0eTZtNWVERFZvUU1EQ3dLa2dnRGFCRjlJNzN3WWVXSkNuS3RhMEFtbDNrTUlTRnhvRjY3aENIamZJWUxXQ0l0bGlIUTJ3SzJtczZYNTdjdDhLREVsU0xMSHpMWW1uRjUvbEtJZWlUVEdXTSt0TXdrd1V3cVhzQmRsbmRBMS9sRm1GWWdzRVZtaVRFWllCK3VwMGZNWmNac1RWcG1GTG5BTWpKbUROOURjRFFFemFYVVJCdEk3Z1JCNTVFYUl5UHFaQ0FjcW9KTDJPTlA3KzJTSko1aDcvN0VzQmNBWGRaZUpweTFsT2p1YkZPRkRyRFEySXBNRkQycUVOcDFWcE5sM2F6NVV6dUZiVFlCZXBMQjJkZVE9PSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiI5OTZkZWYzZC1iMzZjLTQxNTMtODYwNy1hNmZkM2MwMWI4OWYiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkNoYXVkaGFyeSIsImdpdmVuX25hbWUiOiJIYXJkaWsiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyNDA5OjQwYzE6NTAwNTpjNTc6NDE3YTo2Njk3OjhhMzk6MWIwNSIsIm5hbWUiOiJIYXJkaWsgQ2hhdWRoYXJ5Iiwib2lkIjoiYTM1ZGI1ZTAtOWE4Mi00ZGQ3LWExMGYtYWEzMDU1MjczZjczIiwicHVpZCI6IjEwMDMyMDAwODYzQ0Q5RUEiLCJyaCI6IjEuQVNzQVBMdFc3eFdaS2t5eUMzQlRJUjZCX3ozdmJabHNzMU5CaGdlbV9Ud0J1Sl9vQUxVckFBLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZCI6IjAwYjc0OWY5LTM1MWUtMmNlNy01NzMwLWY2YjU0NTdkMWI1YyIsInN1YiI6Ikc1WmN0cGlCTERVWWlQLXIzMVh2aFFDQXBNNk1SVFJmM0M0UXhDR3I3TEEiLCJ0aWQiOiJlZjU2YmIzYy05OTE1LTRjMmEtYjIwYi03MDUzMjExZTgxZmYiLCJ1bmlxdWVfbmFtZSI6ImhhcmRpa0B3ZWNyZWF0ZS5hcHAiLCJ1cG4iOiJoYXJkaWtAd2VjcmVhdGUuYXBwIiwidXRpIjoiYktFSFJ2aGhiMGlEamVWVmtQd25BQSIsInZlciI6IjEuMCIsIndpZHMiOlsiOTYzNzk3ZmItZWIzYi00Y2RlLThjZTMtNTg3OGIzZjMyYTNmIiwiZjI4YTFmNTAtZjZlNy00NTcxLTgxOGItNmExMmYyYWY2YjZjIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19hY3RfZmN0IjoiMyA1IiwieG1zX2Z0ZCI6IlI4T3plYjlOZzVOSHRYWkxuMUl4ZDdINGZEdEpWYTB6c2l5aEhnYjA5UXdCYTI5eVpXRmpaVzUwY21Gc0xXUnpiWE0iLCJ4bXNfaWRyZWwiOiIxIDYiLCJ4bXNfc3ViX2ZjdCI6IjQgMyJ9.VWCGjZWb2RRMbX_A0fxIj0KZBHQTcp8JfAHdG9F46xjhyCSll4EVs71v_kLTaJQhDDJ9DFbv3X9Hsv8vqnlqZjYWwRGJ9VpQbePpuZGjzVo679MJ6k9UbEwrHUy4Ih_bVnzir3d1WMY-amCcVGh2hbtsXKoIuHiiVNLe5NFqXL0lEAUBgxQLwYvVmp1ZVzFcnj2uObQq-E6aPVjhTCtFY-LRpGSOc4Fh7GbgVUDlKd561vLoOpW9JydjXTkLggCo5PZsKmWa3dY4tKAoKti62g2ET7-wEEH1Ut2jpbpurwiANvz7fS8xMEkPW2kVYEUr8oXrWX04VeQUNmxYekFdBA"
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        log("Webhook sent successfully:", await response.text());
    } catch (err) {
        // In real life: retry + queue
        console.error('Webhook failed:', err);
    }
}
